force-app/main/default/objects/InvoiceInformation__c/InvoiceInformation__c.object-meta.xml
<CustomObject>
    <label>請求書情報</label>
    <nameField>
        <displayFormat>{YYYYMM}-{000000}</displayFormat>
        <label>請求書番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/InvoiceInformation__c.field-meta.xml
<CustomField>
    <fullName>InvoiceInformation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>請求書情報</label>
    <referenceTo>InvoiceInformation__c</referenceTo>
    <relationshipLabel>商談</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue__c/Revenue__c.object-meta.xml
<CustomObject>
    <description>Uriage__c</description>
    <label>売上</label>
    <nameField>
        <displayFormat>売上-{00000}</displayFormat>
        <label>売上名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue__c/fields/InvoiceInformation__c.field-meta.xml
<CustomField>
    <fullName>InvoiceInformation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>請求書情報</label>
    <referenceTo>InvoiceInformation__c</referenceTo>
    <relationshipLabel>売上</relationshipLabel>
    <relationshipName>revenues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/B54_SyncRecordsTest.cls
@isTest
private class B54_SyncRecordsTest {

    static testMethod void test() {
        Account acc = new Account(Name='TEST');
        insert acc ;
        
        Opportunity opp = new Opportunity(Name='test', StageName='A', CloseDate=Date.today(), Account=acc );
        insert opp;
        
        List<B54_SyncRecords.Request> requestList = new List<B54_SyncRecords.Request>();
        
        requestList.add( request(acc.Id) );
        requestList.add( request(new LIST<Id>{ acc.Id } ) );
        requestList.add( request(new LIST<Account>{ acc } ) ) ;
        
        B54_SyncRecords.SyncRecords( requestList );
        B54_SyncRecords sync = new B54_SyncRecords( requestList );
        sync.objectName = 'Opportunity' ;
        sync.requestOpportunityRecord(new Opportunity());
        sync.sync();
        sync.objectName = 'OpportunityLineItem' ;
        sync.requestOpportunityLineItemRecord(new OpportunityLineItem());
        sync.sync();
        sync.objectName = 'Revenue__c' ;
        sync.requestUriageRecord(new Revenue__c());
        sync.sync();
        sync.objectName = 'InvoiceInformation__c' ;
        sync.requestSeikyuRecord(new InvoiceInformation__c());
        sync.sync();
    }
    
   
    static B54_SyncRecords.Request request(Id recordId){
        B54_SyncRecords.Request request = new B54_SyncRecords.Request();
        request.recordId = recordId ;
        return request ;
    }
    static B54_SyncRecords.Request request(LIST<Id> recordIds){
        B54_SyncRecords.Request request = new B54_SyncRecords.Request();
        request.recordIds = recordIds ;
        return request ;
    }
    static B54_SyncRecords.Request request(LIST<Sobject> records){
        B54_SyncRecords.Request request = new B54_SyncRecords.Request();
        request.records = records ;
        return request ;
    }
}