force-app/main/default/objects/CloudSignWebHookHistory__c/CloudSignWebHookHistory__c.object-meta.xml
<CustomObject>
    <label>クラウドサインWebHook履歴</label>
    <nameField>
        <label>クラウドサインWebHook履歴名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CloudSignWebHookHistory__c/fields/Json__c.field-meta.xml
<CustomField>
    <fullName>Json__c</fullName>
    <label>JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CloudSignWebHookHistory__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>ステータス</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CloudSignWebHookHistory__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>テキスト</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CloudSignDocumentId__c.field-meta.xml
<CustomField>
    <fullName>CloudSignDocumentId__c</fullName>
    <label>CloudSignドキュメントID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CloudSignStatus__c.field-meta.xml
<CustomField>
    <fullName>CloudSignStatus__c</fullName>
    <label>CloudSign ステータス</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>先方確認中</fullName>
            </value>
            <value>
                <fullName>締結完了</fullName>
            </value>
            <value>
                <fullName>取り消し・却下</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DocumentConfirmationUrl__c.field-meta.xml
<CustomField>
    <fullName>DocumentConfirmationUrl__c</fullName>
    <inlineHelpText>クラウドサイン締結したURLのみを入力してください</inlineHelpText>
    <label>クラウドサインURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/CloudSignWebHookController.cls
@RestResource(urlMapping='/agreements')
global class CloudSignWebHookController {    
    @HttpPost
    global static String doPost() {
        RestRequest req = RestContext.request;
        String reqString = req.requestBody.toString();
        Map<String, Object> reqJson = (Map<String, Object>)JSON.deserializeUntyped(reqString);
        String documentId = (String)reqJson.get('documentID');

        CloudSignWebHookHistory__c webHookHistory = new CloudSignWebHookHistory__c();
        webHookHistory.Text__c = (String)reqJson.get('text');
        webHookHistory.Status__c = (Integer)reqJson.get('status');
        webHookHistory.Json__c = reqString;

        List<Opportunity> oppList = [SELECT Id, CloudSignDocumentId__c, CloudSignStatus__c FROM Opportunity WHERE CloudSignDocumentId__c = :documentId];
        if (oppList.size() > 0) {
            Opportunity opp = oppList[0];
            switch on (Integer)reqJson.get('status') {
                when 1 {
                    opp.CloudSignStatus__c = '先方確認中';
                    opp.StageName = '契約書締結待ち';
                }
                when 2 {
                    opp.CloudSignStatus__c = '締結完了';
                    opp.StageName = '受注';

                    String text = (String)reqJson.get('text');
                    System.debug(text);
                    Integer startIndex = text.indexOf('<');
                    Integer endIndex = text.indexOf('>');
                    if (startIndex != -1 && endIndex != -1) {
                        // URLを取得する
                        String url = text.substring(startIndex + 1, endIndex);
                        System.debug(url); // URLを表示する（デバッグログに出力）
            
                        opp.DocumentConfirmationUrl__c = url;
                    }
                }
                when 3 {
                    opp.CloudSignStatus__c = '取り消し・却下';
                }
                when else {
                    opp.CloudSignStatus__c = '';
                }
            }
            update opp;
        }

        return 'Success';
    }
}